### PR TITLE
ICOB Home Page Search by Inactive Status & CredType

### PR DESCRIPTION
**Pull request by seanadipose**
Add a checkbox on the front page that allows the searching by inactive status and flows through to ensure the checkbox status is maintained to next page.

This now includes changes for the select credential type as well.

### CODE REVIEW

**Comment by ianco** [comment]
On the home page, in the "Search Credentials" drop-down, should list the "translated" credential name rather than the "raw" name (e.g. "Registration" rather than "registration.registries.ca") - this is in en.json

The result page should also show the credential type (e.g. I searched for type "address.registries.ca" and there were no results, however the Search Results page didn't indicate what type I searched nor did it give me the option to change it.

**Comment by swcurran** [comment]
Used the instructions to run the starter kit theme, but it looks like the advanced search link has not been added to that. Does it make sense to add it there?  Difficult?

**Comment by seanadipose** [comment]
> Used the instructions to run the starter kit theme, but it looks like the advanced search link has not been added to that. Does it make sense to add it there? Difficult?

@swcurran 

Hi Stephen, 
I'm working on the advanced search right now. I could close this pull request and open a new one.. but realistically it will not take me much longer to finish the advanced search and I thought that you would not be working today

**Comment by swcurran** [comment]
Sounds good.  Keep going on the getting the advanced search completed.

**Comment by seanadipose** [comment]
@ianco @swcurran 
Completed the advanced search component for review. Note: I did not link it backwards from the main search as all the searching options are already available there anyway, so another advanced search option would be redundant IMO.

**Comment by swcurran** [comment]
Looks good.  Abler to build and run nicely - default theme looks good.  No data, so unable to test the combinations of search types now supported.

Over to Ian to review and merge.

Thanks!

**Comment by ianco** [comment]
Changes required:
- add "Advanced Search" link to search results page
- search isn't returning relationship credentials

**Pull request merged**
