### PR TITLE
Updates to ICOB API's including support for versioning

### PR DESCRIPTION
**Pull request by ianco**
Work is in progress on this topic but opening the PR in Draft mode for visibility and feedback.

General cleanup of the v2 API's.

Support for multiple API versions using middleware = will detect version in an Accept header or in the URL and will map to the appropriate version of the service.  Includes support for things like "default", "latest" or whatever other synonyms we want to support.

The underlying API URL's use the version in the url (such as "/api/v2") however we can hide this in the URL's that we expose.

### CODE REVIEW

**Comment by ianco** [comment]
Ticket is:  https://app.zenhub.com/workspaces/von---verifiable-organization-network-5adf53987ccbaa70597dbec0/issues/bcgov/indy-catalyst/344

**Comment by andrewwhitehead** [comment]
If it's going to use the Accept header, I think the code should split it on commas first, since the header can have multiple values. I'm not sure if the space in the given examples is valid, as in `application/orgbook.bc.api+json; version=v2`.

**Comment by ianco** [comment]
Taking this out of draft for whoever want to work on this next

**Comment by esune** [comment]
PR has become stale, will reopen when ready to move forward.

**Pull request closed without merging**
