### PR TITLE
add new link of the origin of SSI

### PR DESCRIPTION
**Pull request by kdenhartog**
Signed-off-by: Kyle Den Hartog <kdenhar@gmail.com>

### CODE REVIEW

**Comment by kdenhartog** [comment]
Do you know which commit is blocking the merge? From what I can tell all of my commits are DCO signed.

**Comment by ianco** [comment]
9ab3b5e4dd9d49 is signed off but not signed

**Comment by kdenhartog** [comment]
Ok I finally got around to adding GPG signing. This PR Should be good now.

**Comment by kdenhartog** [comment]
Does anyone know why a 1 line change is causing the codecov to drop so significantly? I've not worked with this tool before, so I'm trying to figure out what the cause of it is. I suspect it has to do with the additional code added since I got the signing fixed. I may just close this PR and reopen a new one since it seems the easiest fix.

**Comment by andrewwhitehead** [comment]
@kdenhartog  codecov frequently gets confused about that, clearly it's not correct here. Feel free to open a new PR instead.

**Pull request closed without merging**
