### PR TITLE
Update to use latest credential exchange api

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

### CODE REVIEW

**Comment by ianco** [comment]
An update has been PR'ed into aca-py to support this change, this PR can't proceed until the latest code is updated into a new aca-py release.

**Comment by WadeBarnes** [comment]
@ianco, Please add a link to the associated aca-py PR.

**Comment by ianco** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/384

**Comment by WadeBarnes** [comment]
Looks like the required PR was part of `aca-py 0.4.3`  We're up to `aca-py 0.4.4` now.  Can this come out of draft now?

**Comment by ianco** [comment]
Must be deployed with BC Reg Agent PR https://github.com/bcgov/von-bc-registries-agent/pull/220

**Pull request merged**
