### PR TITLE
Add API version support in accept header

### PR DESCRIPTION
**Pull request by esune**
This continues the work started by @ianco to add support for API versioning in the request, using either path-based versions or requesting a version in the Accept header of the request.

I added unit tests for the middleware, however I am having trouble getting the coverage report to reflect the changes so more updates may be coming.

### CODE REVIEW

**Comment by esune** [comment]
@ianco @andrewwhitehead please don't merge quite yet, I should really have started this in draft mode, but my finger slipped 😅

**Comment by esune** [comment]
Tests are complete (100% coverage of the new code), still trying to get coverage reports to work using the manage command

**Comment by esune** [comment]
It appears that mounting the volumes on the `tob-api` container when running the tests causes the coverage report to be inaccurate - at least on Windows. Working in trying to figure out WHY, other than that this is ready to go.

**Comment by esune** [comment]
@WadeBarnes I believe I will need to tweak the nginx configuration files as well to support more than one API version. I may take a stab at it, but please let me know if you have suggestions/recommendations.

**Comment by esune** [comment]
Before this becomes too old ad goes stale: any feedback/recommendations?
@andrewwhitehead @WadeBarnes @ianco

**Comment by WadeBarnes** [comment]
@esune, I started testing this just before switching gears to performance turning and testing.  I'll come back to it once I get a few more of the performance changes integrated and things are a bit more stable.

**Comment by esune** [comment]
Thanks @WadeBarnes, let me know if you need any more input/support on my end :)

**Comment by andrewwhitehead** [comment]
Looks good to me 💯

**Pull request merged**
