### PR TITLE
Web Hook updates

### PR DESCRIPTION
**Pull request by ianco**
Added docs describing how to use web hooks
Added error handling to hook to update subscription status on success or failure of the hook
Tested other error handling and tracking capabilities of celery

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@ianco, @esune, Just my opinion here ...
I'd prefer to see the API documentation moved into the code where is can be picked up by swagger and displayed as part of the API page.

It's been a while, but here is an example of what swagger can pick up from the code and display on the API page; https://github.com/bcgov/TheOrgBook/blob/dd3f37d1b8c7a7e69b991ab25c1efa3d691e6c0a/tob-api/api/search_views.py#L72

**Comment by ianco** [comment]
@WadeBarnes @esune agree the documentation should be in the code and swagger page.  However we need an overview documentation page for non-developers and that is available without having to read code or run the app to get access to the swagger page.

**Comment by swcurran** [comment]
Agree with both.  We need a "theory of operations" summary that Ian talks about, and once using the swagger, great information for how to use the individual calls.

**Comment by esune** [comment]
@ianco the latest commits add stats for hook delivery. The `/status` endpoint will return one object for each worker, something that looks like this:
```javascript
"web_hook.worker_stats.celery@096e76d59f49": {
        "total_count": 0,
        "attempt_count": 1,
        "success_count": 1,
        "fail_count": 0,
        "retry_count": 0,
        "retry_fail_count": 0
    }
```

**Comment by ianco** [comment]
Tested and working on my local.  Stats need to be confirmed, I'll open a separate issue for that so we can merge this PR.

**Pull request merged**
